# a_tensor_initialization

In [1]:
import torch

In [2]:
# torch.Tensor class
t1 = torch.Tensor([1, 2, 3], device='cpu') # torchFloatTensor와 같은 의미로 float32 dtype으로 tensor 초기화
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False
print(t1.size())  # torch.Size([3])
print(t1.shape)   # torch.Size([3])

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [3]:
# if you have gpu device
# t1_cuda = t1.to(torch.device('cuda'))
# or you can use shorthand
# t1_cuda = t1.cuda()
t1_cpu = t1.cpu() # CPU memory로 tensor를 옮김


In [5]:
print()

In [6]:
# torch.tensor function
t2 = torch.tensor([1, 2, 3], device='cpu') # 소심한 소문자 .tensor 메서드, int64 dtype으로 tensor 초기화
print(t2.dtype)  # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


In [9]:
# if you have gpu device
# t2_cuda = t2.to(torch.device('cuda'))
# or you can use shorthand
# t2_cuda = t2.cuda()
t2_cpu = t2.cpu() # CPU memory로 tensor를 옮김

# b_tensor_initialization_copy

In [10]:
import torch
import numpy as np

In [11]:
l1 = [1, 2, 3]
t1 = torch.Tensor(l1) # dtype float32의 tensor로 초기화

In [12]:
l2 = [1, 2, 3]
t2 = torch.tensor(l2) # dtype int64의 tensor로 초기화

In [13]:
l3 = [1, 2, 3]
t3 = torch.as_tensor(l3) # l3을 tensor로 바꿈

In [20]:
# ⭐️ Tensor initialization의 중요한 특징
# tensor를 초기화하는 메서드의 인자로 사용된 변수의 값을 변경해도 tensor의 값이 변경되지 않는 모습
# torch.Tensor & torch.tensor always copies the given data!
# Imutable하다.
l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)


tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [16]:
print("#" * 100)


####################################################################################################


In [18]:
# numpy는 호환성이 좋음
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
# torch.as_tensor()로 tensor를 초기화할 경우 인자로 전달한 변수와 값을 공유한다.
# Mutable한 list의 특성을 유지하는 모습 (shallow copy)
# t6은 l6을 참조하고 있는 상태로 l6의 요소를 변경하면 t6의 요소도 변경됨
t6 = torch.as_tensor(l6)

In [19]:
l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


# c_tensor_initialization_constant_values

In [21]:
import torch

In [22]:
# size=(5,)는 [*, *, *, *, *]와 같음 (*는 임의의 값)
# 🔨 torch.ones
# Returns a tensor filled with the scalar value 1, with the shape defined by the variable argument size.
t1 = torch.ones(size=(5,))  # or torch.ones(5)

In [23]:
# 🔨 torch.ones_like
# Returns a tensor filled with the scalar value 1, with the same size as input.
# input 파라미터 타입은 tensor이다.
# torch.ones_like는 torch.ones와 동일하다
t1_like = torch.ones_like(input=t1)

In [24]:
print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


In [25]:
# 🔨 torch.zeros
# Returns a tensor filled with the scalar value 0, with the shape defined by the variable argument size.
# 앞선 torch.ones처럼 0으로 차 있는 size shape의 tensor를 반환
t2 = torch.zeros(size=(6,))  # or torch.zeros(6)

In [26]:
# 🔨 torch.zeros_like
# Returns a tensor filled with the scalar value 0, with the same size as input.
# torch.zeros_like 역시 torch.zeros와 같음
t2_like = torch.zeros_like(input=t2)
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])


In [27]:
# 🔨 torch.empty
# Returns a tensor filled with uninitialized data. The shape of the tensor is defined by the variable argument size.
# 초기화 되지 않은 데이터로 tensor를 초기화
t3 = torch.empty(size=(4,))  # or torch.zeros(4)

In [28]:
# 🔨 torch.empty_like
# Returns an uninitialized tensor with the same size as input.
# input 파라미터 타입은 tensor.
t3_like = torch.empty_like(input=t3)
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])

tensor([0., 0., 0., 0.])
tensor([0., 0., 0., 0.])


In [29]:
# 🔨 torch.eye
# Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.
# 2차원 항등행렬(대각선에 1이 있고, 나머지는 0으로 되어 있음) 꼴의 tensor 반환
t4 = torch.eye(n=3)
print(t4)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


# d_tensor_initialization_random_values

In [2]:
import torch

In [3]:
# 🔨 torch.randint
# Returns a tensor filled with random integers generated uniformly between low (inclusive) and high (exclusive).
# 같은 확률로 값이 분포한다!
# low~high 사이의 값이 나온다. (high는 제외)
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

tensor([[16, 10]])


In [4]:
# 🔨 torch.rand
# Returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1)
# 역시 같은 확률로 값이 분포
# 0~1의 값이 발생함 (1은 제외)
t2 = torch.rand(size=(1, 3))
print(t2)

tensor([[0.3559, 0.6967, 0.0988]])


In [6]:
# 🔨 torch.randn
# Returns a tensor filled with random numbers from a normal distribution
# with mean 0 and variance 1 (also called the standard normal distribution).
# 정규분포 비율에 따라 값이 발생 (평균이 0이고 분산이 1인 정규분포, 0에 가까운 값이 더 많이 나옴)
t3 = torch.randn(size=(1, 3))
print(t3)

tensor([[ 0.7918,  1.8548, -1.9091]])


In [7]:
# 🔨 torch.normal
# Returns a tensor of random numbers drawn from separate normal distributions
# whose mean and standard deviation are given.
# 인자로 주어지는 평균, 표준편차에 따른 정규분포 비율에 해당하는 랜덤 값으로 초기화 된 size shape의 tensor 반환
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

tensor([[10.6115, 10.5592],
        [11.7631, 11.0291],
        [10.5083, 10.4379]])


In [8]:
# 🔨 torch.linspace
# Creates a one-dimensional tensor of size steps whose values are evenly spaced from start to end, inclusive.
# start~end 범위에서 steps개 요소를 같은 범위로 뽑아내고 1차원 tensor에 초기화함
t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

tensor([0.0000, 2.5000, 5.0000])


In [9]:
# 🔨 torch.arrange
# Returns a one-dimensional tensor with values from the interval [start, end)
# taken with common difference step beginning from start
# start와 steps는 디폴트값 0, 1로 end값만 주면 0부터 end-1까지 1씩 증가하는 형태로 초기화된 tensor 반환
t6 = torch.arange(5)
print(t6)

tensor([0, 1, 2, 3, 4])


In [11]:
print("#" * 30)

##############################


In [12]:
# 🔨 torch.manual_seed
# It will set teh seed of the random number generator to a fixed value,
# so that when you call for example torch.rand(2), the results will be reproducible.
# 인자로 시드값을 줌으로써 동일한 랜덤값을 얻을 수 있음. 재생산 가능!
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [13]:
random2 = torch.rand(2, 3)
print(random2)

tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [15]:
print()

In [16]:
torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [17]:
random4 = torch.rand(2, 3)
print(random4)

tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


# e_tensor_type_conversion

In [18]:
import torch

In [19]:
# 기본적으로 torch.ones가 리턴하는 tensor의 dtype은 float32
a = torch.ones((2, 3))
print(a.dtype)

torch.float32


In [20]:
# 명시적으로 dtype을 지정할 수 있음
b = torch.ones((2, 3), dtype=torch.int16)
print(b)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [21]:
# torch.rand()는 [0,1)의 값을 반환하는데, 여기에 20이 곱해진 값으로 초기화된 tensor 반환
# broadcasting 발생
c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)

tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)


In [24]:
# (2,3) shape의 tensor를 int32 dtype으로 바꿔서 초기화
d = b.to(torch.int32)
print(d)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [25]:
double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)


In [26]:
print(double_d.dtype)
print(short_e.dtype)

torch.float64
torch.int16


In [28]:
double_f = torch.rand(5, dtype=torch.double)

In [30]:
# torch.short는 torch.int16과 같음
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)

torch.float64


# f_tensor_opertaions

In [32]:
import torch

In [33]:
# Element-wise operations
# Tensor operations는 Element-wise operations이다.
# 각 요소끼리 연산이 진행된다.

In [34]:
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))

In [35]:
t3 = torch.add(t1, t2) # 이것과
t4 = t1 + t2 # 이것은 같다!
print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [37]:
print("#" * 30)

##############################


In [38]:
t5 = torch.sub(t1, t2) # 이것과
t6 = t1 - t2 # 이것은 같다!
print(t5)
print(t6)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [39]:
print("#" * 30)

##############################


In [40]:
t7 = torch.mul(t1, t2) # 이것과
t8 = t1 * t2 # 이것은 같다!
print(t7)
print(t8)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [41]:
print("#" * 30)

##############################


In [42]:
t9 = torch.div(t1, t2) # 이것과
t10 = t1 / t2 # 이것은 같다!
print(t9)
print(t10)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


# g_tensor_operations_mm

In [46]:
import torch

In [47]:
# 🔨 torch.dot
# Computes the dot product of two 1D tensors
# 두 1차원 tensor끼리 내적의 결과
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

tensor(7) torch.Size([])


In [48]:
t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)

In [50]:
# 🔨 torch.mm
# Performs a matrix multiplication without broadcasting
# broadcasting을 하지 않고 행렬 곱을 수행함
print(t2)
print(t3)
t4 = torch.mm(t2, t3)
print(t4, t4.size())

tensor([[ 1.7230, -1.4630, -1.0207],
        [-0.0215, -0.6794, -0.2302]])
tensor([[ 0.4211, -1.6245],
        [ 0.6139,  1.6164],
        [ 1.2499,  1.0061]])
tensor([[-1.4484, -6.1907],
        [-0.7139, -1.2949]]) torch.Size([2, 2])


In [51]:
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)

In [52]:
# 🔨 torch.bmm
# Performs a batch matrix multiplication without broadcasting
# broadcatsing 하지 않고 행렬 곱 수행, input으로 무조건 3차원 tensor가 들어감
t7 = torch.bmm(t5, t6)
print(t7.size())

torch.Size([10, 3, 5])


# h_tensor_operations_mm

In [54]:
import torch

In [55]:
# vector x vector: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([])

torch.Size([])


In [56]:
# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])

torch.Size([3])


In [57]:
# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])

torch.Size([10, 3])


In [58]:
# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])

torch.Size([10, 3, 5])


In [59]:
# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])

torch.Size([10, 3, 5])


# i_tensor_broadcasting

In [60]:
import torch


In [61]:
# Tensor broadcasting
# Element-wise operation을 이해하는 것이 중요하다.

In [62]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2) # 2.0이 각 요소에 broadcasting됨

tensor([2., 4., 6.])


In [63]:
print("#" * 50, 1)

################################################## 1


In [64]:
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5]) # [4, 5]가 t3의 각 행에 broadcasting됨
print(t3 - t4)

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


In [65]:
print("#" * 50, 2)

################################################## 2


In [66]:
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [67]:
print("#" * 50, 3)

################################################## 3


In [68]:
# 인자로 들어온 tensor의 모든 요소에 broadcasting
def normalize(x):
  return x / 255

In [69]:
t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

torch.Size([3, 28, 28])


In [72]:
print("#" * 50, 4)

################################################## 4


In [73]:
t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])

In [74]:
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


In [75]:
print("#" * 50, 5)

################################################## 5


In [76]:
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)

torch.Size([4, 3, 2])


In [77]:
t13 = torch.ones(4, 3, 2) # 1개가 2개에 꽂힘
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)

torch.Size([4, 3, 2])


In [78]:
t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

torch.Size([4, 3, 2])


In [79]:
t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())

torch.Size([5, 3, 4, 1])


In [80]:
print("#" * 50, 6)

################################################## 6


In [81]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

torch.Size([5, 3, 4, 1])


In [82]:
t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

torch.Size([3, 1, 7])


# j_tensor_indexing_slicing

In [2]:
import torch

In [18]:
x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)
print(x[1])  # >>> tensor([5, 6, 7, 8, 9])

tensor([5, 6, 7, 8, 9])


In [5]:
# x의 모든 행을 가져오고 그중에서 1번째 열만 가져옴
# shape는 물론 (3,)임
print(x[:, 1])  # >>> tensor([1, 6, 11])
print(x[1, 2])  # >>> tensor(7)
print(x[:, -1])  # >>> tensor([4, 9, 14)

tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


In [6]:
print("#" * 50, 1)

################################################## 1


In [7]:
print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])


In [8]:
print("#" * 50, 2)

################################################## 2


In [9]:
y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


In [10]:
print(y[1:4, 1:4])

tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


In [11]:
print("#" * 50, 3)

################################################## 3


In [17]:
z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])


In [16]:
z[1:, 1:3] = 0
print(z)

tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


# k_tensor_reshaping

In [19]:
import torch

In [22]:
# 🔨 torch.view
# Returns a new tensor with the same data as the self tensor but of a different shape.
# Tensor의 shape를 바꿔서 반환
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # Shape becomes (3, 2)

In [23]:
# 🔨 torch.reshape
# torch.view와 기능은 같지만 tensor의 copy를 반환한다.
# 즉 view는 값을 공유하고 reshape는 복사된 새로운 값을 반환한다.
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)

In [24]:
print(t2)
print(t3)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])


In [25]:
# 똑같은 메모리에서 사용하기 때문에 좋은 코드이다. 나중에 잘 활용할 것!
t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)

In [26]:
print(t4)
print(t5)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [27]:
print("#" * 50, 1)

################################################## 1


In [30]:
# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

In [32]:
# 🔨 torch.squeeze
# Returns a tensor with all specified dimensions of input of size 1 removed.
# 말 그대로 tensor를 쥐어짜서 차원이 1인 부분을 제거함
# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,)

In [33]:
# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)

In [34]:
print(t7)
print(t8)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])


In [35]:
print("#" * 50, 2)


################################################## 2


In [36]:
# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

In [37]:
# 🔨 torch.unsqueeze
# Adds a new dimension to the tensor at the specified position
# 지정한 위치에 차원을 확장한다.
# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10)

tensor([[1],
        [2],
        [3]])


In [38]:
t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


In [39]:
print("#" * 50, 3)

################################################## 3


In [40]:
# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [41]:
# 🔨 torch.flatten
# Flattens input by reshaping it into a one-dimensional tensor
# 1차원 tensor로 평평하게 만들어줌
# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,)

print(t14)

tensor([1, 2, 3, 4, 5, 6])


In [42]:
# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)

tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [43]:
print("#" * 50, 4)

################################################## 4


In [44]:
# 🔨 torch.permute
# permute는 순서화시키다라는 의미를 가짐
# Returns a view of the original tensor input with its dimensions permuted
# 인자로 주어지는 차원 순서로 tensor의 shape를 바꿈
# view를 리턴하기 때문에 sharing
t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])


In [45]:
# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [46]:
# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [47]:
# 🔨 torch.transpose
# The given dimensions dim0 and dim1 are swapped
# 특정 차원 2개를 바꿈
# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)

print(t22)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [48]:
# 🔨 torch.t
# It expects input to be 2D tensor and transposes dimensions 0 and 1
# input으로 2D tensor가 들어가며, 해당 tensor를 transpose함.
# 전치행렬과 같음
t23 = torch.t(t19)  # Shape becomes (3, 2)

print(t23)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


# i_tensor_concat

In [49]:
import torch

In [50]:
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

In [51]:
# 🔨 torch.cat, torch.concat
# It takes a sequence of tensors and concatenates them along the specified dimension, resulting in a new tensor.
# 지정된 차원을 따라 tensor끼리 연결하여 새로운 tensor 생성
t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)

torch.Size([2, 6, 3])


In [52]:
print("#" * 50, 1)

################################################## 1


In [53]:
t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

In [54]:
t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [55]:
print("#" * 50, 2)

################################################## 2


In [56]:
t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

In [57]:
# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


In [58]:
t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)

torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [59]:
print("#" * 50, 3)

################################################## 3


In [60]:
t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

In [61]:
t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])


In [62]:
t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)

torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [63]:
print("#" * 50, 4)

################################################## 4


In [64]:
t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

In [65]:
t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])


In [66]:
t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)

torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])


In [67]:
t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)

torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


# m_tensor_stacking

In [68]:
import torch

In [71]:
# 🔨 torch.stack
# It takes a sequence of tensors and stacks them along a new dimension,
# creating a new tensor with one additional dimension
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])# 새로운 차원으로 확장하여 tensor sequence를 병합

In [72]:
t3 = torch.stack([t1, t2], dim=0)

In [73]:
# unsqueeze로 새로운 차원을 만든 후, 두 tensor를 새로운 차원 기준으로 합침 == torch.stack
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)

In [74]:
print(t3.shape, t3.equal(t4))

torch.Size([2, 2, 3]) True


In [75]:
t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

torch.Size([2, 2, 3]) True


In [76]:
t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

torch.Size([2, 3, 2]) True


In [77]:
print("#" * 50, 1)

################################################## 1


In [78]:
t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())

torch.Size([3]) torch.Size([3])


In [79]:
t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)

torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [80]:
t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))

True


In [81]:
t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)

torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [82]:
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))

True


# n_tensor_vstack_hstack

In [11]:
import torch

In [12]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [13]:
t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))

In [14]:
t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)

torch.Size([2, 2, 3])


In [15]:
t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)

torch.Size([2, 2, 3])


In [16]:
t9 = torch.vstack([t7, t8])
print(t9.shape)

torch.Size([4, 2, 3])


In [17]:
print(t9)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])


In [90]:
print("#" * 50, 1)

################################################## 1


In [18]:
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)

tensor([1, 2, 3, 4, 5, 6])


In [19]:
t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [20]:
t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)

torch.Size([2, 2, 3])


In [21]:
t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)

torch.Size([2, 2, 3])


In [22]:
t18 = torch.hstack([t16, t17])
print(t18.shape)

torch.Size([2, 4, 3])


In [23]:
print(t18)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


# 기술적 사항과 고찰

이번 과제를 통해 어떤 배움이든 도움이 된다고 느꼈다. 특히 텐서의 여러가지 메서드 중 항등 행렬을 만드는 `torch.eye` 메서드를 보면서
선형대수를 공부했던 기억이 났다. 또한 `torch.view`는 값을 공유하고 `torch.reshape`는 tensor의 copy를 반환한다는 점을 통해
기본적인 파이썬 개념도 다시금 되짚어보게 됐다. 수업 시간에 deepcopy 관련해서 질문이 있었고 교수님이 이 질문을 칭찬하시면서 잘 생각해봐야 한다고 하셨는데,
앞으로도 torch 메서드를 사용하면서 이 메서드가 어떤 타입의 인자를 받아서 어떤 값을 반환하는지 확실하게 익힐 필요가 있을 듯하다.
추가로 torch 메서드를 공부하면서 파이토치 공식 문서가 많은 도움이 됐다. 영어로 되어 있지만 이해하는 데에는 큰 무리가 없었고 무엇보다도 정확하고 확실하게 이해할 수 있어서 좋았다.

# 숙제_후기

딥러닝및실습 과목은 생각했던 것보다 확실히 쉽지 않다. 
이번 과제는 텐서의 다양한 메서드로 텐서를 가지고 놀아보는 시간이었다.
텐서가 메서드가 이렇게 많을 줄 몰랐다. 이것들을 하나하나 외울 순 없겠지만 이렇게 하나씩 경험하고 나중에 필요할 때 파이토치 공식 문서를 보며
문제를 해결할 수 있을 거 같다. 